wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.14.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681369339.196159
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.1
      5: 0.14.2
      8:
      - 3
      - 5
