wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.14.2
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681200781.077656
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.1
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
