name: Train and Test Model

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "./Landslide Deploment/requirements.txt"

    - name: Login to Wandb
      run: wandb login ${{ secrets.WANDB_API_KEY }}
      
    - name: Train and Test Model
      run: |
        dvc remote add -d dvc_gdrive gdrive://1zqtDlwB7kEpRGfz26sPX15wNs9lieK9P
        python "./Landslide Deploment/model.py"
        dvc add "./Landslide Deploment/LandslideRF.pkl" "./Landslide Deploment/bhutan_landslide_data.csv"
        dvc push -r dvc_gdrive

    - name: Get changes
        run: |
          git status -uno

      - uses: EndBug/add-and-commit@v7
        with:
          add: .
          author_name: CI-CD Pipeline run
          author_email: klhendup01@gmail.com
          message: "adding changes from run"
